//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clairvoyance.Services.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleDeckListsJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleDeckListsJson() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clairvoyance.Services.Tests.Resources.SampleDeckListsJson", typeof(SampleDeckListsJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Bane of Bala Ged&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{7}&quot;,
        ///      &quot;Cmc&quot;:7.0,
        ///      &quot;Colors&quot;:null,
        ///      &quot;ColorIdentity&quot;:null,
        ///      &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///      &quot;Supertypes&quot;:null,
        ///      &quot;Types&quot;:[  
        ///         &quot;Creature&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Eldrazi&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///      &quot;Text&quot;:&quot;Whenever Bane of Bala Ged attacks, defending player exiles two permanents he or she controls.&quot;,
        ///      &quot;Flavor&quot;:&quot;The continent of Bala Ged was r [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CanGetAvailableMana {
            get {
                return ResourceManager.GetString("CanGetAvailableMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Nissa, Steward of Elements&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{X}{G}{U}&quot;,
        ///      &quot;Cmc&quot;:2.0,
        ///      &quot;Colors&quot;:[  
        ///         &quot;Blue&quot;,
        ///         &quot;Green&quot;
        ///      ],
        ///      &quot;ColorIdentity&quot;:[  
        ///         &quot;U&quot;,
        ///         &quot;G&quot;
        ///      ],
        ///      &quot;Type&quot;:&quot;Legendary Planeswalker — Nissa&quot;,
        ///      &quot;Supertypes&quot;:[  
        ///         &quot;Legendary&quot;
        ///      ],
        ///      &quot;Types&quot;:[  
        ///         &quot;Planeswalker&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Nissa&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Mythic Rare&quot;,
        ///      &quot;Text&quot;:&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Desolation {
            get {
                return ResourceManager.GetString("Desolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TODO.
        /// </summary>
        internal static string SampleWithAftermathLayout {
            get {
                return ResourceManager.GetString("SampleWithAftermathLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Nissa, Steward of Elements&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{X}{G}{U}&quot;,
        ///      &quot;Cmc&quot;:2.0,
        ///      &quot;Colors&quot;:[  
        ///         &quot;Blue&quot;,
        ///         &quot;Green&quot;
        ///      ],
        ///      &quot;ColorIdentity&quot;:[  
        ///         &quot;U&quot;,
        ///         &quot;G&quot;
        ///      ],
        ///      &quot;Type&quot;:&quot;Legendary Planeswalker — Nissa&quot;,
        ///      &quot;Supertypes&quot;:[  
        ///         &quot;Legendary&quot;
        ///      ],
        ///      &quot;Types&quot;:[  
        ///         &quot;Planeswalker&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Nissa&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Mythic Rare&quot;,
        ///      &quot;Text&quot;:&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SimpleSample {
            get {
                return ResourceManager.GetString("SimpleSample", resourceCulture);
            }
        }
    }
}
