//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clairvoyance.Services.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleDeckListsJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleDeckListsJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clairvoyance.Services.Tests.SampleDeckListsJson", typeof(SampleDeckListsJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Bane of Bala Ged&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{7}&quot;,
        ///      &quot;Cmc&quot;:7.0,
        ///      &quot;Colors&quot;:null,
        ///      &quot;ColorIdentity&quot;:null,
        ///      &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///      &quot;Supertypes&quot;:null,
        ///      &quot;Types&quot;:[  
        ///         &quot;Creature&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Eldrazi&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///      &quot;Text&quot;:&quot;Whenever Bane of Bala Ged attacks, defending player exiles two permanents he or she controls.&quot;,
        ///      &quot;Flavor&quot;:&quot;The continent of Bala Ged was r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CanGetAvailableMana {
            get {
                return ResourceManager.GetString("CanGetAvailableMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Nissa, Steward of Elements&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{X}{G}{U}&quot;,
        ///      &quot;Cmc&quot;:2.0,
        ///      &quot;Colors&quot;:[  
        ///         &quot;Blue&quot;,
        ///         &quot;Green&quot;
        ///      ],
        ///      &quot;ColorIdentity&quot;:[  
        ///         &quot;U&quot;,
        ///         &quot;G&quot;
        ///      ],
        ///      &quot;Type&quot;:&quot;Legendary Planeswalker — Nissa&quot;,
        ///      &quot;Supertypes&quot;:[  
        ///         &quot;Legendary&quot;
        ///      ],
        ///      &quot;Types&quot;:[  
        ///         &quot;Planeswalker&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Nissa&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Mythic Rare&quot;,
        ///      &quot;Text&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Desolation {
            get {
                return ResourceManager.GetString("Desolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        internal static string SampleWithAftermathLayout {
            get {
                return ResourceManager.GetString("SampleWithAftermathLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [  
        ///   {  
        ///      &quot;Name&quot;:&quot;Nissa, Steward of Elements&quot;,
        ///      &quot;Names&quot;:null,
        ///      &quot;ManaCost&quot;:&quot;{X}{G}{U}&quot;,
        ///      &quot;Cmc&quot;:2.0,
        ///      &quot;Colors&quot;:[  
        ///         &quot;Blue&quot;,
        ///         &quot;Green&quot;
        ///      ],
        ///      &quot;ColorIdentity&quot;:[  
        ///         &quot;U&quot;,
        ///         &quot;G&quot;
        ///      ],
        ///      &quot;Type&quot;:&quot;Legendary Planeswalker — Nissa&quot;,
        ///      &quot;Supertypes&quot;:[  
        ///         &quot;Legendary&quot;
        ///      ],
        ///      &quot;Types&quot;:[  
        ///         &quot;Planeswalker&quot;
        ///      ],
        ///      &quot;Subtypes&quot;:[  
        ///         &quot;Nissa&quot;
        ///      ],
        ///      &quot;Rarity&quot;:&quot;Mythic Rare&quot;,
        ///      &quot;Text&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleSample {
            get {
                return ResourceManager.GetString("SimpleSample", resourceCulture);
            }
        }
    }
}
