//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clairvoyance.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardJson() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clairvoyance.Tests.Resources.CardJson", typeof(CardJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Bane of Bala Ged&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{7}&quot;,
        ///  &quot;Cmc&quot;:7.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Whenever Bane of Bala Ged attacks, defending player exiles two permanents he or she controls.&quot;,
        ///  &quot;Flavor&quot;:&quot;The continent of Bala Ged was ravaged by massive Eldrazi of Ulamog&apos;s lineage, its lush jungles and cascading rive [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string BaneOfBalaGed {
            get {
                return ResourceManager.GetString("BaneOfBalaGed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Conduit of Ruin&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{6}&quot;,
        ///  &quot;Cmc&quot;:6.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;When you cast Conduit of Ruin, you may search your library for a colorless creature card with converted mana cost 7 or greater, reveal it, then shuffle your library and put that card on top of it.\nThe first creature spell you  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ConduitOfRuin {
            get {
                return ResourceManager.GetString("ConduitOfRuin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Deceiver of Form&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{6}{C}&quot;,
        ///  &quot;Cmc&quot;:7.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;({C} represents colorless mana.)\nAt the beginning of combat on your turn, reveal the top card of your library. If a creature card is revealed this way, you may have creatures you control other than Deceiver of Form become  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DeceiverOfForm {
            get {
                return ResourceManager.GetString("DeceiverOfForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Deepfathom Skulker&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{5}{U}&quot;,
        ///  &quot;Cmc&quot;:6.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;U&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;Devoid (This card has no color.)\nWhenever a creature you control deals combat damage to a player, you may draw a card.\n{3}{C}: Target creature can&apos;t be blocked this turn. ({C} represents colorless mana.)&quot;,
        ///  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DeepfathomSkulker {
            get {
                return ResourceManager.GetString("DeepfathomSkulker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Desolation Twin&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{10}&quot;,
        ///  &quot;Cmc&quot;:10.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;When you cast Desolation Twin, create a 10/10 colorless Eldrazi creature token.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;With precise coordination and enough blood spilled, one can be driven off, even brought down. But two . . . that&apos;s a lot of bloo [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DesolationTwin {
            get {
                return ResourceManager.GetString("DesolationTwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Elvish Spirit Guide&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{2}{G}&quot;,
        ///  &quot;Cmc&quot;:3.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Elf Spirit&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Elf&quot;,
        ///	 &quot;Spirit&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Exile Elvish Spirit Guide from your hand: Add {G} to your mana pool.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;We are never without guidance, if we but seek it.\&quot;\n—Taaveti of Kelsinko, Elvish Hunter&quot;,
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ElvishSpiritGuide {
            get {
                return ResourceManager.GetString("ElvishSpiritGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Endbringer&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{5}{C}&quot;,
        ///  &quot;Cmc&quot;:6.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;Untap Endbringer during each other player&apos;s untap step.\n{T}: Endbringer deals 1 damage to target creature or player.\n{C}, {T}: Target creature can&apos;t attack or block this turn.\n{C}{C}, {T}: Draw a card.&quot;,
        ///  &quot;Flavor&quot;:null,
        ///  &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Endbringer {
            get {
                return ResourceManager.GetString("Endbringer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Forest&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Basic Land — Forest&quot;,
        ///  &quot;Supertypes&quot;:[  
        ///	 &quot;Basic&quot;
        ///  ],
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Forest&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Basic Land&quot;,
        ///  &quot;Text&quot;:null,
        ///  &quot;Flavor&quot;:null,
        ///  &quot;Artist&quot;:&quot;John Avon&quot;,
        ///  &quot;Number&quot;:&quot;246&quot;,
        ///  &quot;Power&quot;:null,
        ///  &quot;Toughness&quot;:null,
        ///  &quot;Loyalty&quot;:null,
        ///  &quot;Layout&quot;:&quot;normal&quot;,
        ///  &quot;Multiverseid&quot;:195158,
        ///  &quot;Variations&quot;:[  
        ///	 &quot;201962&quot;,
        ///	 &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Ghost Quarter&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{T}, Sacrifice Ghost Quarter: Destroy target land. Its controller may search his or her library for a basic land card, put it onto the battlefield, then shuffle his or her library.&quot;,
        ///  &quot;Flavor&quot;:&quot;Deserted, but not uninhabited.&quot;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string GhostQuarter {
            get {
                return ResourceManager.GetString("GhostQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Hedron Archive&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{4}&quot;,
        ///  &quot;Cmc&quot;:4.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Artifact&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Artifact&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C}{C} to your mana pool.\n{2}, {T}, Sacrifice Hedron Archive: Draw two cards.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;You&apos;ve begun to understand the hedrons&apos; true purpose,\&quot; said Ugin. \&quot;The Eldrazi can be imprisoned.\&quot;\&quot;And how did that work out last time?\&quot; aske [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string HedronArchive {
            get {
                return ResourceManager.GetString("HedronArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Island&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;U&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Basic Land — Island&quot;,
        ///  &quot;Supertypes&quot;:[  
        ///	 &quot;Basic&quot;
        ///  ],
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Island&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Basic Land&quot;,
        ///  &quot;Text&quot;:null,
        ///  &quot;Flavor&quot;:null,
        ///  &quot;Artist&quot;:&quot;John Avon&quot;,
        ///  &quot;Number&quot;:&quot;234&quot;,
        ///  &quot;Power&quot;:null,
        ///  &quot;Toughness&quot;:null,
        ///  &quot;Loyalty&quot;:null,
        ///  &quot;Layout&quot;:&quot;normal&quot;,
        ///  &quot;Multiverseid&quot;:195187,
        ///  &quot;Variations&quot;:[  
        ///	 &quot;195170&quot;,
        ///	 &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Island {
            get {
                return ResourceManager.GetString("Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Llanowar Elves&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{G}&quot;,
        ///  &quot;Cmc&quot;:1.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Elf Druid&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Elf&quot;,
        ///	 &quot;Druid&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Common&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {G} to your mana pool.&quot;,
        ///  &quot;Flavor&quot;:&quot;One bone broken for every twig snapped underfoot.\n—Llanowar penalty for trespassing&quot;,
        ///  &quot;Artist&quot;:&quot;Kev Walker&quot;,
        ///  &quot;Number&quot;:&quot;182&quot;,
        ///  &quot;Power&quot;: [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string LlanowarElves {
            get {
                return ResourceManager.GetString("LlanowarElves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Lotus Petal&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{0}&quot;,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Artifact&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Artifact&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Special&quot;,
        ///  &quot;Text&quot;:&quot;{T}, Sacrifice Lotus Petal: Add one mana of any color to your mana pool.&quot;,
        ///  &quot;Flavor&quot;:&quot;Each of these intricate mechanical petals stores enough power to supply all of Ghirapur, if only for a fleeting moment.&quot;,
        ///  &quot;Artist&quot;:&quot;Slawomir Maniak&quot;,
        ///  &quot;Number&quot;:&quot;1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string LotusPetal {
            get {
                return ResourceManager.GetString("LotusPetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Magus of the Library&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{G}{G}&quot;,
        ///  &quot;Cmc&quot;:2.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Human Wizard&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Human&quot;,
        ///	 &quot;Wizard&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{T}: Draw a card. Activate this ability only if you have exactly seven cards in hand.&quot;,
        ///  &quot;Flavor&quot;:&quot;The ancient books slowly crumbled, their se [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MagusOfTheLibrary {
            get {
                return ResourceManager.GetString("MagusOfTheLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Mishra&apos;s Factory&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{1}: Mishra&apos;s Factory becomes a 2/2 Assembly-Worker artifact creature until end of turn. It&apos;s still a land.\n{T}: Target Assembly-Worker creature gets +1/+1 until end of turn.&quot;,
        ///  &quot;Flavor&quot;:null,
        ///  &quot;Artist&quot;:&quot;Kaja &amp; Phil Foglio&quot;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MishrasFactory {
            get {
                return ResourceManager.GetString("MishrasFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Nissa, Steward of Elements&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{X}{G}{U}&quot;,
        ///  &quot;Cmc&quot;:2.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Blue&quot;,
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;U&quot;,
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Legendary Planeswalker — Nissa&quot;,
        ///  &quot;Supertypes&quot;:[  
        ///	 &quot;Legendary&quot;
        ///  ],
        ///  &quot;Types&quot;:[  
        ///	 &quot;Planeswalker&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Nissa&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Mythic Rare&quot;,
        ///  &quot;Text&quot;:&quot;+2: Scry 2.\n0: Look at the top card of your library. If it&apos;s a land card or a creature card with converted mana cost less th [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string NissaStewardOfElements {
            get {
                return ResourceManager.GetString("NissaStewardOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Prophet of Distortion&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{U}&quot;,
        ///  &quot;Cmc&quot;:1.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;U&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi Drone&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;,
        ///	 &quot;Drone&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Devoid (This card has no color.)\n{3}{C}: Draw a card. ({C} represents colorless mana.)&quot;,
        ///  &quot;Flavor&quot;:&quot;It doesn&apos;t twist words. It twists worlds.&quot;,
        ///  &quot;Artist&quot;:&quot;Lius Lasahido&quot;,
        ///  &quot;Number&quot;: [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ProphetOfDistortion {
            get {
                return ResourceManager.GetString("ProphetOfDistortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Pulse of Murasa&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{2}{G}&quot;,
        ///  &quot;Cmc&quot;:3.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Instant&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Instant&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Common&quot;,
        ///  &quot;Text&quot;:&quot;Return target creature or land card from a graveyard to its owner&apos;s hand. You gain 6 life.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;Little flower twirl and bloom, arise from this your rocky tomb. Little warrior slash and brawl, be born again to free [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string PulseOfMurasa {
            get {
                return ResourceManager.GetString("PulseOfMurasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Spatial Contortion&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{1}{C}&quot;,
        ///  &quot;Cmc&quot;:2.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Instant&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Instant&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;({C} represents colorless mana.)\nTarget creature gets +3/-3 until end of turn.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;For those without the Planeswalker spark, the merest touch of the Blind Eternities can kill.\&quot;\n—Ugin&quot;,
        ///  &quot;Artist&quot;:&quot;Daarken&quot;,
        ///  &quot;Number&quot;:&quot;8&quot;,
        ///  &quot;P [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string SpatialContortion {
            get {
                return ResourceManager.GetString("SpatialContortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Spawning Bed&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{6}, {T}, Sacrifice Spawning Bed: Create three 1/1 colorless Eldrazi Scion creature tokens. They have \&quot;Sacrifice this creature: Add {C} to your mana pool.\&quot;&quot;,
        ///  &quot;Flavor&quot;:&quot;Young Eldrazi crawl forth from the dust, compelled by a  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string SpawningBed {
            get {
                return ResourceManager.GetString("SpawningBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Thought-Knot Seer&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{3}{C}&quot;,
        ///  &quot;Cmc&quot;:4.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;({C} represents colorless mana.)\nWhen Thought-Knot Seer enters the battlefield, target opponent reveals his or her hand. You choose a nonland card from it and exile that card.\nWhen Thought-Knot Seer leaves the battlefiel [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string ThoughtKnotSeer {
            get {
                return ResourceManager.GetString("ThoughtKnotSeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Unclaimed Territory&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;As Unclaimed Territory enters the battlefield, choose a creature type.\n{T}: Add {C} to your mana pool.\n{T}: Add one mana of any color to your mana pool. Spend this mana only to cast a creature spell of the chosen type.&quot;,
        ///  &quot;Flavor&quot;:null,
        ///  &quot;Artist&quot;:&quot;D [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string UnclaimedTerritory {
            get {
                return ResourceManager.GetString("UnclaimedTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Void Grafter&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{1}{G}{U}&quot;,
        ///  &quot;Cmc&quot;:3.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;U&quot;,
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi Drone&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;,
        ///	 &quot;Drone&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Devoid (This card has no color.)\nFlash (You may cast this spell any time you could cast an instant.)\nWhen Void Grafter enters the battlefield, another target creature you control ga [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string VoidGrafter {
            get {
                return ResourceManager.GetString("VoidGrafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Worldly Tutor&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{G}&quot;,
        ///  &quot;Cmc&quot;:1.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Instant&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Instant&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Search your library for a creature card and reveal that card. Shuffle your library, then put the card on top of it.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;Aselbo soon had the rhino eating from his palm and the snake waiting at his heels.\&quot;\n—Afari, T [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string WorldlyTutor {
            get {
                return ResourceManager.GetString("WorldlyTutor", resourceCulture);
            }
        }
    }
}
